services:
  go_db_app:
    container_name: go_db_app
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=anangs123
      - POSTGRES_USER=root
      - POSTGRES_DB=go_apps
    volumes:
      - pddata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - restoran

networks:
  restoran:
    driver: bridge

volumes:
  pddata: