services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=anangs123
      - POSTGRES_USER=root
      - POSTGRES_DB=crypto_wallet
    volumes:
      - pddata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - wallet

networks:
  wallet:
    driver: bridge

volumes:
  pddata: